# -*- coding: utf-8 -*-
"""Copy of Unemployment analysis with python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JdhmhNg_G-D8Hr7e_B9sTcWIjKVzHiu6
"""

import pandas as pd
import numpy as np

df=pd.read_csv("Unemployment_Rate_upto_11_2020.csv")

df.head()

df.tail()

df.shape

df.info()

df.describe()

x=df["Region"]

x

y= df[" Estimated Unemployment Rate (%)"]

y

df2 = df.iloc[:,3]

df2

import plotly.express as px
import matplotlib.pyplot as plt

fg= px.bar(df,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',
           title ='Unemployment Rate(State Wise)by Bar Graph',template= 'plotly')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()

fg= px.box(df,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',
           title ='Unemployment Rate(State Wise)by Bar Graph',template= 'plotly')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()